### ISSUE TITLE
pip install fails on Mac M1 arm64 

### ISSUE THREAD

**Issue by ace-han** [MatPoliquin/stable-retro#11]
## Issue summary

```
pip install  git+https://github.com/MatPoliquin/stable-retro.git
Collecting git+https://github.com/MatPoliquin/stable-retro.git
  Cloning https://github.com/MatPoliquin/stable-retro.git to /private/var/folders/9z/p1jwllm56lvc3csp3f_k1f0h0000gp/T/pip-req-build-47adzf2x
  Running command git clone --filter=blob:none --quiet https://github.com/MatPoliquin/stable-retro.git /private/var/folders/9z/p1jwllm56lvc3csp3f_k1f0h0000gp/T/pip-req-build-47adzf2x
  Resolved https://github.com/MatPoliquin/stable-retro.git to commit 90fa6f8d46416a0151d90e26296468d2f627740e
  Preparing metadata (setup.py) ... done
Requirement already satisfied: gymnasium>=0.27.1 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from gym-retro==0.8.0.dev79+g90fa6f8) (0.27.1)
Requirement already satisfied: pyglet==1.*,>=1.3.2 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from gym-retro==0.8.0.dev79+g90fa6f8) (1.5.27)
Requirement already satisfied: numpy>=1.21.0 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from gymnasium>=0.27.1->gym-retro==0.8.0.dev79+g90fa6f8) (1.24.2)
Requirement already satisfied: typing-extensions>=4.3.0 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from gymnasium>=0.27.1->gym-retro==0.8.0.dev79+g90fa6f8) (4.5.0)
Requirement already satisfied: gymnasium-notices>=0.0.1 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from gymnasium>=0.27.1->gym-retro==0.8.0.dev79+g90fa6f8) (0.0.1)
Requirement already satisfied: jax-jumpy>=0.2.0 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from gymnasium>=0.27.1->gym-retro==0.8.0.dev79+g90fa6f8) (0.2.0)
Requirement already satisfied: importlib-metadata>=4.8.0 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from gymnasium>=0.27.1->gym-retro==0.8.0.dev79+g90fa6f8) (6.0.0)
Requirement already satisfied: cloudpickle>=1.2.0 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from gymnasium>=0.27.1->gym-retro==0.8.0.dev79+g90fa6f8) (2.2.1)
Requirement already satisfied: zipp>=0.5 in /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages (from importlib-metadata>=4.8.0->gymnasium>=0.27.1->gym-retro==0.8.0.dev79+g90fa6f8) (3.15.0)
Building wheels for collected packages: gym-retro
  Building wheel for gym-retro (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7835 lines of output]
      /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13.1-arm64-cpython-38
      creating build/lib.macosx-13.1-arm64-cpython-38/retro
      copying retro/enums.py -> build/lib.macosx-13.1-arm64-cpython-38/retro


... tons of copying and creating logs ...
... tons of copying and creating logs ...
... tons of copying and creating logs ...

copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/scenario.json -> build/lib.macosx-13.1-arm64-cpython-38/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
      copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/rom.sha -> build/lib.macosx-13.1-arm64-cpython-38/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
      running build_ext
      CMake Warning:
        Ignoring empty string ("") provided on the command line.
      
      
      CMake Deprecation Warning at third-party/gtest/googlemock/CMakeLists.txt:46 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Deprecation Warning at third-party/gtest/googletest/CMakeLists.txt:53 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      /Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      -- Configuring done (0.5s)
      -- Generating done (0.3s)
      -- Build files have been written to: /private/var/folders/9z/p1jwllm56lvc3csp3f_k1f0h0000gp/T/pip-req-build-i7twcd_e
      [  0%] Generating build/lib.macosx-13.1-arm64-cpython-38/retro/cores/mednafen_pce_fast_libretro.dylib
      [  0%] Generating build/lib.macosx-13.1-arm64-cpython-38/retro/cores/mgba_libretro.dylib
      [  4%] Generating build/lib.macosx-13.1-arm64-cpython-38/retro/cores/genesis_plus_gx_libretro.dylib
      [  4%] Generating build/lib.macosx-13.1-arm64-cpython-38/retro/cores/stella_libretro.dylib
      [  8%] Generating build/lib.macosx-13.1-arm64-cpython-38/retro/cores/gambatte_libretro.dylib
      [ 12%] Generating build/lib.macosx-13.1-arm64-cpython-38/retro/cores/fceumm_libretro.dylib
      [ 12%] Generating build/lib.macosx-13.1-arm64-cpython-38/retro/cores/snes9x_libretro.dylib
      [ 83%] Built target zip
      In file included from libgambatte/src/bootloader.cpp:2:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
      #include_next <string.h>
                    ^~~~~~~~~~
      In file included from libgambatte/src/cpu.cpp:19:
      In file included from libgambatte/src/cpu.h:22:
      In file included from libgambatte/src/../include/gambatte.h:27:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:519:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      In file included from libgambatte/src/gambatte.cpp:19:
      In file included from libgambatte/src/../include/gambatte.h:27:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:519:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      In file included from libgambatte/src/initstate.cpp:23:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:649:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      In file included from src/arm/arm.c:6:
      In file included from ./include/mgba/internal/arm/arm.h:9:
      ./include/mgba-util/common.h:19:10: fatal error: 'ctype.h' file not found
      #include <ctype.h>
               ^~~~~~~~~
      1 error generated.
      make[4]: *** [src/arm/arm.o] Error 1
      make[3]: *** [build/lib.macosx-13.1-arm64-cpython-38/retro/cores/mgba_libretro.dylib] Error 2
      In file included from mednafen/pce_fast/huc6280.cpp:18:
      In file included from mednafen/pce_fast/pce.h:4:
      mednafen/pce_fast/../mednafen-types.h:4:10: fatal error: 'assert.h' file not found
      #include <assert.h>
               ^~~~~~~~~~
      make[2]: *** [CMakeFiles/gba.dir/all] Error 2
      make[2]: *** Waiting for unfinished jobs....
      In file included from ../apu/apu.cpp:190:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/math.h:300:15: fatal error: 'math.h' file not found
      #include_next <math.h>
                    ^~~~~~~~
      In file included from libgambatte/src/interrupter.cpp:19:
      In file included from libgambatte/src/interrupter.h:22:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:519:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      In file included from stella/src/common/Base.cxx:20:
      In file included from stella/src/common/Base.hxx:23:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iostream:37:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:214:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:15:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:519:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      core/cd_hw/libchdr/src/bitstream.c:13:10: fatal error: 'stdlib.h' file not found
      #include <stdlib.h>
               ^~~~~~~~~~
      1 error generated.
      1 error generated.
      make[4]: *** [core/cd_hw/libchdr/src/bitstream.o] Error 1
      make[4]: *** [libgambatte/src/initstate.o] Error 1
      make[4]: *** Waiting for unfinished jobs....
      1 error generated.
      make[3]: *** [build/lib.macosx-13.1-arm64-cpython-38/retro/cores/genesis_plus_gx_libretro.dylib] Error 2
      make[2]: *** [CMakeFiles/genesis.dir/all] Error 2
      make[4]: *** [libgambatte/src/bootloader.o] Error 1
      In file included from src/boards/01-222.c:36:
      In file included from src/boards/mapinc.h:3:
      In file included from src/boards/../fceu.h:71:
      src/driver.h:4:10: fatal error: 'stdio.h' file not found
      #include <stdio.h>
               ^~~~~~~~~
      1 error generated.
      make[4]: *** [src/boards/01-222.o] Error 1
      make[3]: *** [build/lib.macosx-13.1-arm64-cpython-38/retro/cores/fceumm_libretro.dylib] Error 2
      make[2]: *** [CMakeFiles/nes.dir/all] Error 2
      1 error generated.
      make[4]: *** [libgambatte/src/cpu.o] Error 1
      In file included from mednafen/pce_fast/input.cpp:18:
      In file included from mednafen/pce_fast/pce.h:4:
      mednafen/pce_fast/../mednafen-types.h:4:10: fatal error: 'assert.h' file not found
      #include <assert.h>
               ^~~~~~~~~~
      1 error generated.
      In file included from mednafen/pce_fast/pcecd.cpp:26:
      In file included from mednafen/pce_fast/../mednafen.h:4:
      ./mednafen/mednafen-types.h:4:10: fatal error: 'assert.h' file not found
      #include <assert.h>
               ^~~~~~~~~~
      make[4]: *** [libgambatte/src/gambatte.o] Error 1
      In file included from ../apu/bapu/dsp/sdsp.cpp:1:
      In file included from ../apu/bapu/snes/snes.hpp:4:
      In file included from ../snes9x.h:195:
      In file included from ../port.h:191:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdio.h:107:15: fatal error: 'stdio.h' file not found
      #include_next <stdio.h>
                    ^~~~~~~~~
      In file included from stella/src/common/SoundSDL.cxx:22:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/sstream:184:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/istream:163:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ostream:137:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/bitset:116:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__bit_reference:15:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:649:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      In file included from mednafen/pce_fast/pcecd_drive.cpp:18:
      In file included from mednafen/pce_fast/../mednafen.h:4:
      ./mednafen/mednafen-types.h:4:10: fatal error: 'assert.h' file not found
      #include <assert.h>
               ^~~~~~~~~~
      1 error generated.
      1 error generated.
      make[4]: *** [../apu/apu.o] Error 1
      make[4]: *** Waiting for unfinished jobs....
      1 error generated.
      make[4]: *** [libgambatte/src/interrupter.o] Error 1
      make[3]: *** [build/lib.macosx-13.1-arm64-cpython-38/retro/cores/gambatte_libretro.dylib] Error 2
      make[2]: make[4]: *** [mednafen/pce_fast/huc6280.o] Error 1
      make[4]: *** Waiting for unfinished jobs....
      *** [CMakeFiles/gb.dir/all] Error 2
      In file included from ../apu/bapu/dsp/SPC_DSP.cpp:3:
      In file included from ../apu/bapu/dsp/SPC_DSP.h:7:
      In file included from ../apu/bapu/dsp/blargg_common.h:9:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdlib.h:93:15: fatal error: 'stdlib.h' file not found
      #include_next <stdlib.h>
                    ^~~~~~~~~~
      1 error generated.
      make[4]: *** [../apu/bapu/dsp/SPC_DSP.o] Error 1
      1 error generated.
      make[4]: *** [stella/src/common/Base.o] Error 1
      make[4]: *** Waiting for unfinished jobs....
      In file included from stella/src/emucore/Cart.cxx:20:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cassert:20:10: fatal error: 'assert.h' file not found
      #include <assert.h>
               ^~~~~~~~~~
      In file included from stella/src/emucore/Booster.cxx:20:
      In file included from stella/src/emucore/Event.hxx:23:
      In file included from stella/src/common/bspf.hxx:64:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:649:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      In file included from stella/src/emucore/AtariVox.cxx:20:
      In file included from stella/src/emucore/MT24LC256.hxx:26:
      In file included from stella/src/common/bspf.hxx:64:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:649:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      In file included from stella/src/emucore/Cart0840.cxx:20:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cassert:20:10: fatal error: 'assert.h' file not found
      #include <assert.h>
               ^~~~~~~~~~
      1 error generated.
      make[4]: *** [../apu/bapu/dsp/sdsp.o] Error 1
      make[3]: *** [build/lib.macosx-13.1-arm64-cpython-38/retro/cores/snes9x_libretro.dylib] Error 2
      make[2]: *** [CMakeFiles/snes.dir/all] Error 2
      1 error generated.
      make[4]: *** [mednafen/pce_fast/input.o] Error 1
      1 error generated.
      make[4]: *** [mednafen/pce_fast/pcecd.o] Error 1
      1 error generated.
      make[4]: *** [mednafen/pce_fast/pcecd_drive.o] Error 1
      1 error generated.
      make[3]: *** [build/lib.macosx-13.1-arm64-cpython-38/retro/cores/mednafen_pce_fast_libretro.dylib] Error 2
      make[2]: *** [CMakeFiles/pce.dir/all] Error 2
      make[4]: *** [stella/src/common/SoundSDL.o] Error 1
      1 error generated.
      1 error generated.
      make[4]: *** [stella/src/emucore/Booster.o] Error 1
      make[4]: *** [stella/src/emucore/AtariVox.o] Error 1
      1 error generated.
      make[4]: *** [stella/src/emucore/Cart.o] Error 1
      1 error generated.
      make[4]: *** [stella/src/emucore/Cart0840.o] Error 1
      make[3]: *** [build/lib.macosx-13.1-arm64-cpython-38/retro/cores/stella_libretro.dylib] Error 2
      make[2]: *** [CMakeFiles/atari2600.dir/all] Error 2
      make[1]: *** [CMakeFiles/retro.dir/rule] Error 2
      make: *** [retro] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/9z/p1jwllm56lvc3csp3f_k1f0h0000gp/T/pip-req-build-i7twcd_e/setup.py", line 74, in <module>
          setup(
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/Users/ace/Library/Caches/pypoetry/virtualenvs/tutorials-kDNQVN1r-py3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/9z/p1jwllm56lvc3csp3f_k1f0h0000gp/T/pip-req-build-i7twcd_e/setup.py", line 64, in run
          subprocess.check_call([make_exe, jobs, 'retro'])
        File "/Users/ace/.pyenv/versions/3.8.16/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/make', '-j10', 'retro']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gym-retro

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

## System information

- [Operating system] macOS 13.1 Darwin 22.2.0
- [Python version] Python 3.8.16
- [Gym Retro version] https://github.com/MatPoliquin/stable-retro/commit/90fa6f8d46416a0151d90e26296468d2f627740e (should be the latest of this repo)

**Comment by arvganesh** [comment]
Have the same issue. I've tried using both native ARM and rosetta and still wasn't able to get it to install on OS X 12.5 with Python 3.8.16.

**Comment by zbeucler2018** [comment]
This issue has a little more [attention on the original repo](https://github.com/openai/retro/issues/264)

**Comment by arvganesh** [comment]
I think `wchar.h not found` and `stdio.h not found` have to do with the OS X SDK path:

Here are some links with similar issues:
- https://stackoverflow.com/questions/26185978/macos-wchar-h-file-not-found
- https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/issues/1055#issuecomment-581920327
- https://stackoverflow.com/questions/60128120/how-can-i-solve-this-error-on-macos-catalina
